/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ingress.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ingress.pb-c.h"
void   ingress__tag_value_str_list__init
                     (Ingress__TagValueStrList         *message)
{
  static const Ingress__TagValueStrList init_value = INGRESS__TAG_VALUE_STR_LIST__INIT;
  *message = init_value;
}
size_t ingress__tag_value_str_list__get_packed_size
                     (const Ingress__TagValueStrList *message)
{
  assert(message->base.descriptor == &ingress__tag_value_str_list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ingress__tag_value_str_list__pack
                     (const Ingress__TagValueStrList *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ingress__tag_value_str_list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ingress__tag_value_str_list__pack_to_buffer
                     (const Ingress__TagValueStrList *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ingress__tag_value_str_list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ingress__TagValueStrList *
       ingress__tag_value_str_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ingress__TagValueStrList *)
     protobuf_c_message_unpack (&ingress__tag_value_str_list__descriptor,
                                allocator, len, data);
}
void   ingress__tag_value_str_list__free_unpacked
                     (Ingress__TagValueStrList *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ingress__tag_value_str_list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ingress__tag_item_condition__init
                     (Ingress__TagItemCondition         *message)
{
  static const Ingress__TagItemCondition init_value = INGRESS__TAG_ITEM_CONDITION__INIT;
  *message = init_value;
}
size_t ingress__tag_item_condition__get_packed_size
                     (const Ingress__TagItemCondition *message)
{
  assert(message->base.descriptor == &ingress__tag_item_condition__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ingress__tag_item_condition__pack
                     (const Ingress__TagItemCondition *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ingress__tag_item_condition__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ingress__tag_item_condition__pack_to_buffer
                     (const Ingress__TagItemCondition *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ingress__tag_item_condition__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ingress__TagItemCondition *
       ingress__tag_item_condition__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ingress__TagItemCondition *)
     protobuf_c_message_unpack (&ingress__tag_item_condition__descriptor,
                                allocator, len, data);
}
void   ingress__tag_item_condition__free_unpacked
                     (Ingress__TagItemCondition *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ingress__tag_item_condition__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ingress__tag_item__init
                     (Ingress__TagItem         *message)
{
  static const Ingress__TagItem init_value = INGRESS__TAG_ITEM__INIT;
  *message = init_value;
}
size_t ingress__tag_item__get_packed_size
                     (const Ingress__TagItem *message)
{
  assert(message->base.descriptor == &ingress__tag_item__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ingress__tag_item__pack
                     (const Ingress__TagItem *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ingress__tag_item__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ingress__tag_item__pack_to_buffer
                     (const Ingress__TagItem *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ingress__tag_item__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ingress__TagItem *
       ingress__tag_item__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ingress__TagItem *)
     protobuf_c_message_unpack (&ingress__tag_item__descriptor,
                                allocator, len, data);
}
void   ingress__tag_item__free_unpacked
                     (Ingress__TagItem *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ingress__tag_item__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ingress__tag_rule__init
                     (Ingress__TagRule         *message)
{
  static const Ingress__TagRule init_value = INGRESS__TAG_RULE__INIT;
  *message = init_value;
}
size_t ingress__tag_rule__get_packed_size
                     (const Ingress__TagRule *message)
{
  assert(message->base.descriptor == &ingress__tag_rule__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ingress__tag_rule__pack
                     (const Ingress__TagRule *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ingress__tag_rule__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ingress__tag_rule__pack_to_buffer
                     (const Ingress__TagRule *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ingress__tag_rule__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ingress__TagRule *
       ingress__tag_rule__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ingress__TagRule *)
     protobuf_c_message_unpack (&ingress__tag_rule__descriptor,
                                allocator, len, data);
}
void   ingress__tag_rule__free_unpacked
                     (Ingress__TagRule *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ingress__tag_rule__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ingress__tag_router__init
                     (Ingress__TagRouter         *message)
{
  static const Ingress__TagRouter init_value = INGRESS__TAG_ROUTER__INIT;
  *message = init_value;
}
size_t ingress__tag_router__get_packed_size
                     (const Ingress__TagRouter *message)
{
  assert(message->base.descriptor == &ingress__tag_router__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ingress__tag_router__pack
                     (const Ingress__TagRouter *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ingress__tag_router__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ingress__tag_router__pack_to_buffer
                     (const Ingress__TagRouter *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ingress__tag_router__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ingress__TagRouter *
       ingress__tag_router__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ingress__TagRouter *)
     protobuf_c_message_unpack (&ingress__tag_router__descriptor,
                                allocator, len, data);
}
void   ingress__tag_router__free_unpacked
                     (Ingress__TagRouter *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ingress__tag_router__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ingress__path_router__init
                     (Ingress__PathRouter         *message)
{
  static const Ingress__PathRouter init_value = INGRESS__PATH_ROUTER__INIT;
  *message = init_value;
}
size_t ingress__path_router__get_packed_size
                     (const Ingress__PathRouter *message)
{
  assert(message->base.descriptor == &ingress__path_router__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ingress__path_router__pack
                     (const Ingress__PathRouter *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ingress__path_router__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ingress__path_router__pack_to_buffer
                     (const Ingress__PathRouter *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ingress__path_router__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ingress__PathRouter *
       ingress__path_router__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ingress__PathRouter *)
     protobuf_c_message_unpack (&ingress__path_router__descriptor,
                                allocator, len, data);
}
void   ingress__path_router__free_unpacked
                     (Ingress__PathRouter *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ingress__path_router__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ingress__host_router__init
                     (Ingress__HostRouter         *message)
{
  static const Ingress__HostRouter init_value = INGRESS__HOST_ROUTER__INIT;
  *message = init_value;
}
size_t ingress__host_router__get_packed_size
                     (const Ingress__HostRouter *message)
{
  assert(message->base.descriptor == &ingress__host_router__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ingress__host_router__pack
                     (const Ingress__HostRouter *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ingress__host_router__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ingress__host_router__pack_to_buffer
                     (const Ingress__HostRouter *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ingress__host_router__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ingress__HostRouter *
       ingress__host_router__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ingress__HostRouter *)
     protobuf_c_message_unpack (&ingress__host_router__descriptor,
                                allocator, len, data);
}
void   ingress__host_router__free_unpacked
                     (Ingress__HostRouter *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ingress__host_router__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ingress__appname_router__init
                     (Ingress__AppnameRouter         *message)
{
  static const Ingress__AppnameRouter init_value = INGRESS__APPNAME_ROUTER__INIT;
  *message = init_value;
}
size_t ingress__appname_router__get_packed_size
                     (const Ingress__AppnameRouter *message)
{
  assert(message->base.descriptor == &ingress__appname_router__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ingress__appname_router__pack
                     (const Ingress__AppnameRouter *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ingress__appname_router__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ingress__appname_router__pack_to_buffer
                     (const Ingress__AppnameRouter *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ingress__appname_router__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ingress__AppnameRouter *
       ingress__appname_router__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ingress__AppnameRouter *)
     protobuf_c_message_unpack (&ingress__appname_router__descriptor,
                                allocator, len, data);
}
void   ingress__appname_router__free_unpacked
                     (Ingress__AppnameRouter *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ingress__appname_router__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ingress__apirouter__init
                     (Ingress__APIRouter         *message)
{
  static const Ingress__APIRouter init_value = INGRESS__APIROUTER__INIT;
  *message = init_value;
}
size_t ingress__apirouter__get_packed_size
                     (const Ingress__APIRouter *message)
{
  assert(message->base.descriptor == &ingress__apirouter__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ingress__apirouter__pack
                     (const Ingress__APIRouter *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ingress__apirouter__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ingress__apirouter__pack_to_buffer
                     (const Ingress__APIRouter *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ingress__apirouter__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ingress__APIRouter *
       ingress__apirouter__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ingress__APIRouter *)
     protobuf_c_message_unpack (&ingress__apirouter__descriptor,
                                allocator, len, data);
}
void   ingress__apirouter__free_unpacked
                     (Ingress__APIRouter *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ingress__apirouter__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ingress__router__init
                     (Ingress__Router         *message)
{
  static const Ingress__Router init_value = INGRESS__ROUTER__INIT;
  *message = init_value;
}
size_t ingress__router__get_packed_size
                     (const Ingress__Router *message)
{
  assert(message->base.descriptor == &ingress__router__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ingress__router__pack
                     (const Ingress__Router *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ingress__router__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ingress__router__pack_to_buffer
                     (const Ingress__Router *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ingress__router__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ingress__Router *
       ingress__router__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ingress__Router *)
     protobuf_c_message_unpack (&ingress__router__descriptor,
                                allocator, len, data);
}
void   ingress__router__free_unpacked
                     (Ingress__Router *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ingress__router__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ingress__timeout__init
                     (Ingress__Timeout         *message)
{
  static const Ingress__Timeout init_value = INGRESS__TIMEOUT__INIT;
  *message = init_value;
}
size_t ingress__timeout__get_packed_size
                     (const Ingress__Timeout *message)
{
  assert(message->base.descriptor == &ingress__timeout__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ingress__timeout__pack
                     (const Ingress__Timeout *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ingress__timeout__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ingress__timeout__pack_to_buffer
                     (const Ingress__Timeout *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ingress__timeout__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ingress__Timeout *
       ingress__timeout__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ingress__Timeout *)
     protobuf_c_message_unpack (&ingress__timeout__descriptor,
                                allocator, len, data);
}
void   ingress__timeout__free_unpacked
                     (Ingress__Timeout *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ingress__timeout__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ingress__upstream__init
                     (Ingress__Upstream         *message)
{
  static const Ingress__Upstream init_value = INGRESS__UPSTREAM__INIT;
  *message = init_value;
}
size_t ingress__upstream__get_packed_size
                     (const Ingress__Upstream *message)
{
  assert(message->base.descriptor == &ingress__upstream__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ingress__upstream__pack
                     (const Ingress__Upstream *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ingress__upstream__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ingress__upstream__pack_to_buffer
                     (const Ingress__Upstream *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ingress__upstream__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ingress__Upstream *
       ingress__upstream__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ingress__Upstream *)
     protobuf_c_message_unpack (&ingress__upstream__descriptor,
                                allocator, len, data);
}
void   ingress__upstream__free_unpacked
                     (Ingress__Upstream *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ingress__upstream__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ingress__metadata__init
                     (Ingress__Metadata         *message)
{
  static const Ingress__Metadata init_value = INGRESS__METADATA__INIT;
  *message = init_value;
}
size_t ingress__metadata__get_packed_size
                     (const Ingress__Metadata *message)
{
  assert(message->base.descriptor == &ingress__metadata__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ingress__metadata__pack
                     (const Ingress__Metadata *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ingress__metadata__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ingress__metadata__pack_to_buffer
                     (const Ingress__Metadata *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ingress__metadata__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ingress__Metadata *
       ingress__metadata__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ingress__Metadata *)
     protobuf_c_message_unpack (&ingress__metadata__descriptor,
                                allocator, len, data);
}
void   ingress__metadata__free_unpacked
                     (Ingress__Metadata *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ingress__metadata__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ingress__action__init
                     (Ingress__Action         *message)
{
  static const Ingress__Action init_value = INGRESS__ACTION__INIT;
  *message = init_value;
}
size_t ingress__action__get_packed_size
                     (const Ingress__Action *message)
{
  assert(message->base.descriptor == &ingress__action__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ingress__action__pack
                     (const Ingress__Action *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ingress__action__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ingress__action__pack_to_buffer
                     (const Ingress__Action *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ingress__action__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ingress__Action *
       ingress__action__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ingress__Action *)
     protobuf_c_message_unpack (&ingress__action__descriptor,
                                allocator, len, data);
}
void   ingress__action__free_unpacked
                     (Ingress__Action *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ingress__action__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ingress__unit_redirect__init
                     (Ingress__UnitRedirect         *message)
{
  static const Ingress__UnitRedirect init_value = INGRESS__UNIT_REDIRECT__INIT;
  *message = init_value;
}
size_t ingress__unit_redirect__get_packed_size
                     (const Ingress__UnitRedirect *message)
{
  assert(message->base.descriptor == &ingress__unit_redirect__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ingress__unit_redirect__pack
                     (const Ingress__UnitRedirect *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ingress__unit_redirect__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ingress__unit_redirect__pack_to_buffer
                     (const Ingress__UnitRedirect *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ingress__unit_redirect__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ingress__UnitRedirect *
       ingress__unit_redirect__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ingress__UnitRedirect *)
     protobuf_c_message_unpack (&ingress__unit_redirect__descriptor,
                                allocator, len, data);
}
void   ingress__unit_redirect__free_unpacked
                     (Ingress__UnitRedirect *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ingress__unit_redirect__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ingress__unit_weight__init
                     (Ingress__UnitWeight         *message)
{
  static const Ingress__UnitWeight init_value = INGRESS__UNIT_WEIGHT__INIT;
  *message = init_value;
}
size_t ingress__unit_weight__get_packed_size
                     (const Ingress__UnitWeight *message)
{
  assert(message->base.descriptor == &ingress__unit_weight__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ingress__unit_weight__pack
                     (const Ingress__UnitWeight *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ingress__unit_weight__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ingress__unit_weight__pack_to_buffer
                     (const Ingress__UnitWeight *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ingress__unit_weight__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ingress__UnitWeight *
       ingress__unit_weight__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ingress__UnitWeight *)
     protobuf_c_message_unpack (&ingress__unit_weight__descriptor,
                                allocator, len, data);
}
void   ingress__unit_weight__free_unpacked
                     (Ingress__UnitWeight *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ingress__unit_weight__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ingress__unit__init
                     (Ingress__Unit         *message)
{
  static const Ingress__Unit init_value = INGRESS__UNIT__INIT;
  *message = init_value;
}
size_t ingress__unit__get_packed_size
                     (const Ingress__Unit *message)
{
  assert(message->base.descriptor == &ingress__unit__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ingress__unit__pack
                     (const Ingress__Unit *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ingress__unit__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ingress__unit__pack_to_buffer
                     (const Ingress__Unit *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ingress__unit__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ingress__Unit *
       ingress__unit__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ingress__Unit *)
     protobuf_c_message_unpack (&ingress__unit__descriptor,
                                allocator, len, data);
}
void   ingress__unit__free_unpacked
                     (Ingress__Unit *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ingress__unit__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ingress__redirect__init
                     (Ingress__Redirect         *message)
{
  static const Ingress__Redirect init_value = INGRESS__REDIRECT__INIT;
  *message = init_value;
}
size_t ingress__redirect__get_packed_size
                     (const Ingress__Redirect *message)
{
  assert(message->base.descriptor == &ingress__redirect__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ingress__redirect__pack
                     (const Ingress__Redirect *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ingress__redirect__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ingress__redirect__pack_to_buffer
                     (const Ingress__Redirect *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ingress__redirect__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ingress__Redirect *
       ingress__redirect__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ingress__Redirect *)
     protobuf_c_message_unpack (&ingress__redirect__descriptor,
                                allocator, len, data);
}
void   ingress__redirect__free_unpacked
                     (Ingress__Redirect *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ingress__redirect__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ingress__failover_rule__init
                     (Ingress__FailoverRule         *message)
{
  static const Ingress__FailoverRule init_value = INGRESS__FAILOVER_RULE__INIT;
  *message = init_value;
}
size_t ingress__failover_rule__get_packed_size
                     (const Ingress__FailoverRule *message)
{
  assert(message->base.descriptor == &ingress__failover_rule__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ingress__failover_rule__pack
                     (const Ingress__FailoverRule *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ingress__failover_rule__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ingress__failover_rule__pack_to_buffer
                     (const Ingress__FailoverRule *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ingress__failover_rule__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ingress__FailoverRule *
       ingress__failover_rule__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ingress__FailoverRule *)
     protobuf_c_message_unpack (&ingress__failover_rule__descriptor,
                                allocator, len, data);
}
void   ingress__failover_rule__free_unpacked
                     (Ingress__FailoverRule *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ingress__failover_rule__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ingress__failover__init
                     (Ingress__Failover         *message)
{
  static const Ingress__Failover init_value = INGRESS__FAILOVER__INIT;
  *message = init_value;
}
size_t ingress__failover__get_packed_size
                     (const Ingress__Failover *message)
{
  assert(message->base.descriptor == &ingress__failover__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ingress__failover__pack
                     (const Ingress__Failover *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ingress__failover__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ingress__failover__pack_to_buffer
                     (const Ingress__Failover *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ingress__failover__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ingress__Failover *
       ingress__failover__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ingress__Failover *)
     protobuf_c_message_unpack (&ingress__failover__descriptor,
                                allocator, len, data);
}
void   ingress__failover__free_unpacked
                     (Ingress__Failover *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ingress__failover__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ingress__virtual_service__init
                     (Ingress__VirtualService         *message)
{
  static const Ingress__VirtualService init_value = INGRESS__VIRTUAL_SERVICE__INIT;
  *message = init_value;
}
size_t ingress__virtual_service__get_packed_size
                     (const Ingress__VirtualService *message)
{
  assert(message->base.descriptor == &ingress__virtual_service__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ingress__virtual_service__pack
                     (const Ingress__VirtualService *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ingress__virtual_service__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ingress__virtual_service__pack_to_buffer
                     (const Ingress__VirtualService *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ingress__virtual_service__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ingress__VirtualService *
       ingress__virtual_service__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ingress__VirtualService *)
     protobuf_c_message_unpack (&ingress__virtual_service__descriptor,
                                allocator, len, data);
}
void   ingress__virtual_service__free_unpacked
                     (Ingress__VirtualService *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ingress__virtual_service__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ingress__expire_time__init
                     (Ingress__ExpireTime         *message)
{
  static const Ingress__ExpireTime init_value = INGRESS__EXPIRE_TIME__INIT;
  *message = init_value;
}
size_t ingress__expire_time__get_packed_size
                     (const Ingress__ExpireTime *message)
{
  assert(message->base.descriptor == &ingress__expire_time__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ingress__expire_time__pack
                     (const Ingress__ExpireTime *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ingress__expire_time__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ingress__expire_time__pack_to_buffer
                     (const Ingress__ExpireTime *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ingress__expire_time__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ingress__ExpireTime *
       ingress__expire_time__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ingress__ExpireTime *)
     protobuf_c_message_unpack (&ingress__expire_time__descriptor,
                                allocator, len, data);
}
void   ingress__expire_time__free_unpacked
                     (Ingress__ExpireTime *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ingress__expire_time__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ingress__host_cert_entry__init
                     (Ingress__HostCertEntry         *message)
{
  static const Ingress__HostCertEntry init_value = INGRESS__HOST_CERT_ENTRY__INIT;
  *message = init_value;
}
size_t ingress__host_cert_entry__get_packed_size
                     (const Ingress__HostCertEntry *message)
{
  assert(message->base.descriptor == &ingress__host_cert_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ingress__host_cert_entry__pack
                     (const Ingress__HostCertEntry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ingress__host_cert_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ingress__host_cert_entry__pack_to_buffer
                     (const Ingress__HostCertEntry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ingress__host_cert_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ingress__HostCertEntry *
       ingress__host_cert_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ingress__HostCertEntry *)
     protobuf_c_message_unpack (&ingress__host_cert_entry__descriptor,
                                allocator, len, data);
}
void   ingress__host_cert_entry__free_unpacked
                     (Ingress__HostCertEntry *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ingress__host_cert_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ingress__config__init
                     (Ingress__Config         *message)
{
  static const Ingress__Config init_value = INGRESS__CONFIG__INIT;
  *message = init_value;
}
size_t ingress__config__get_packed_size
                     (const Ingress__Config *message)
{
  assert(message->base.descriptor == &ingress__config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ingress__config__pack
                     (const Ingress__Config *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ingress__config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ingress__config__pack_to_buffer
                     (const Ingress__Config *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ingress__config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ingress__Config *
       ingress__config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ingress__Config *)
     protobuf_c_message_unpack (&ingress__config__descriptor,
                                allocator, len, data);
}
void   ingress__config__free_unpacked
                     (Ingress__Config *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ingress__config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor ingress__tag_value_str_list__field_descriptors[1] =
{
  {
    "value",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Ingress__TagValueStrList, n_value),
    offsetof(Ingress__TagValueStrList, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ingress__tag_value_str_list__field_indices_by_name[] = {
  0,   /* field[0] = value */
};
static const ProtobufCIntRange ingress__tag_value_str_list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ingress__tag_value_str_list__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ingress.TagValueStrList",
  "TagValueStrList",
  "Ingress__TagValueStrList",
  "Ingress",
  sizeof(Ingress__TagValueStrList),
  1,
  ingress__tag_value_str_list__field_descriptors,
  ingress__tag_value_str_list__field_indices_by_name,
  1,  ingress__tag_value_str_list__number_ranges,
  (ProtobufCMessageInit) ingress__tag_value_str_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ingress__tag_item_condition__field_descriptors[5] =
{
  {
    "value_str",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ingress__TagItemCondition, value_str),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value_list",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ingress__TagItemCondition, value_list),
    &ingress__tag_value_str_list__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "divisor",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Ingress__TagItemCondition, has_divisor),
    offsetof(Ingress__TagItemCondition, divisor),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "remainder",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Ingress__TagItemCondition, has_remainder),
    offsetof(Ingress__TagItemCondition, remainder),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "operator",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Ingress__TagItemCondition, has_operator_),
    offsetof(Ingress__TagItemCondition, operator_),
    &ingress__operator_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ingress__tag_item_condition__field_indices_by_name[] = {
  2,   /* field[2] = divisor */
  4,   /* field[4] = operator */
  3,   /* field[3] = remainder */
  1,   /* field[1] = value_list */
  0,   /* field[0] = value_str */
};
static const ProtobufCIntRange ingress__tag_item_condition__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor ingress__tag_item_condition__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ingress.TagItemCondition",
  "TagItemCondition",
  "Ingress__TagItemCondition",
  "Ingress",
  sizeof(Ingress__TagItemCondition),
  5,
  ingress__tag_item_condition__field_descriptors,
  ingress__tag_item_condition__field_indices_by_name,
  1,  ingress__tag_item_condition__number_ranges,
  (ProtobufCMessageInit) ingress__tag_item_condition__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ingress__tag_item__field_descriptors[4] =
{
  {
    "location",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Ingress__TagItem, has_location),
    offsetof(Ingress__TagItem, location),
    &ingress__location_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ingress__TagItem, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "condition",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ingress__TagItem, condition),
    &ingress__tag_item_condition__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "match_type",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Ingress__TagItem, has_match_type),
    offsetof(Ingress__TagItem, match_type),
    &ingress__match_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ingress__tag_item__field_indices_by_name[] = {
  2,   /* field[2] = condition */
  1,   /* field[1] = key */
  0,   /* field[0] = location */
  3,   /* field[3] = match_type */
};
static const ProtobufCIntRange ingress__tag_item__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor ingress__tag_item__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ingress.TagItem",
  "TagItem",
  "Ingress__TagItem",
  "Ingress",
  sizeof(Ingress__TagItem),
  4,
  ingress__tag_item__field_descriptors,
  ingress__tag_item__field_indices_by_name,
  1,  ingress__tag_item__number_ranges,
  (ProtobufCMessageInit) ingress__tag_item__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ingress__tag_rule__field_descriptors[1] =
{
  {
    "items",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ingress__TagRule, n_items),
    offsetof(Ingress__TagRule, items),
    &ingress__tag_item__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ingress__tag_rule__field_indices_by_name[] = {
  0,   /* field[0] = items */
};
static const ProtobufCIntRange ingress__tag_rule__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ingress__tag_rule__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ingress.TagRule",
  "TagRule",
  "Ingress__TagRule",
  "Ingress",
  sizeof(Ingress__TagRule),
  1,
  ingress__tag_rule__field_descriptors,
  ingress__tag_rule__field_indices_by_name,
  1,  ingress__tag_rule__number_ranges,
  (ProtobufCMessageInit) ingress__tag_rule__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ingress__tag_router__field_descriptors[2] =
{
  {
    "service_name",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ingress__TagRouter, service_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rules",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ingress__TagRouter, n_rules),
    offsetof(Ingress__TagRouter, rules),
    &ingress__tag_rule__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ingress__tag_router__field_indices_by_name[] = {
  1,   /* field[1] = rules */
  0,   /* field[0] = service_name */
};
static const ProtobufCIntRange ingress__tag_router__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ingress__tag_router__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ingress.TagRouter",
  "TagRouter",
  "Ingress__TagRouter",
  "Ingress",
  sizeof(Ingress__TagRouter),
  2,
  ingress__tag_router__field_descriptors,
  ingress__tag_router__field_indices_by_name,
  1,  ingress__tag_router__number_ranges,
  (ProtobufCMessageInit) ingress__tag_router__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ingress__path_router__field_descriptors[3] =
{
  {
    "prefix",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ingress__PathRouter, prefix),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "service_name",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ingress__PathRouter, service_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tags",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ingress__PathRouter, n_tags),
    offsetof(Ingress__PathRouter, tags),
    &ingress__tag_router__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ingress__path_router__field_indices_by_name[] = {
  0,   /* field[0] = prefix */
  1,   /* field[1] = service_name */
  2,   /* field[2] = tags */
};
static const ProtobufCIntRange ingress__path_router__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ingress__path_router__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ingress.PathRouter",
  "PathRouter",
  "Ingress__PathRouter",
  "Ingress",
  sizeof(Ingress__PathRouter),
  3,
  ingress__path_router__field_descriptors,
  ingress__path_router__field_indices_by_name,
  1,  ingress__path_router__number_ranges,
  (ProtobufCMessageInit) ingress__path_router__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ingress__host_router__field_descriptors[5] =
{
  {
    "host",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ingress__HostRouter, host),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "service_name",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ingress__HostRouter, service_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "paths",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ingress__HostRouter, n_paths),
    offsetof(Ingress__HostRouter, paths),
    &ingress__path_router__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tags",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ingress__HostRouter, n_tags),
    offsetof(Ingress__HostRouter, tags),
    &ingress__tag_router__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Ingress__HostRouter, has_type),
    offsetof(Ingress__HostRouter, type),
    &ingress__host_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ingress__host_router__field_indices_by_name[] = {
  0,   /* field[0] = host */
  2,   /* field[2] = paths */
  1,   /* field[1] = service_name */
  3,   /* field[3] = tags */
  4,   /* field[4] = type */
};
static const ProtobufCIntRange ingress__host_router__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor ingress__host_router__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ingress.HostRouter",
  "HostRouter",
  "Ingress__HostRouter",
  "Ingress",
  sizeof(Ingress__HostRouter),
  5,
  ingress__host_router__field_descriptors,
  ingress__host_router__field_indices_by_name,
  1,  ingress__host_router__number_ranges,
  (ProtobufCMessageInit) ingress__host_router__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ingress__appname_router__field_descriptors[3] =
{
  {
    "appname",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ingress__AppnameRouter, appname),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "service_name",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ingress__AppnameRouter, service_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tags",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ingress__AppnameRouter, n_tags),
    offsetof(Ingress__AppnameRouter, tags),
    &ingress__tag_router__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ingress__appname_router__field_indices_by_name[] = {
  0,   /* field[0] = appname */
  1,   /* field[1] = service_name */
  2,   /* field[2] = tags */
};
static const ProtobufCIntRange ingress__appname_router__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ingress__appname_router__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ingress.AppnameRouter",
  "AppnameRouter",
  "Ingress__AppnameRouter",
  "Ingress",
  sizeof(Ingress__AppnameRouter),
  3,
  ingress__appname_router__field_descriptors,
  ingress__appname_router__field_indices_by_name,
  1,  ingress__appname_router__number_ranges,
  (ProtobufCMessageInit) ingress__appname_router__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ingress__apirouter__field_descriptors[3] =
{
  {
    "service_name",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ingress__APIRouter, service_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "api",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ingress__APIRouter, api),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tags",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ingress__APIRouter, n_tags),
    offsetof(Ingress__APIRouter, tags),
    &ingress__tag_router__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ingress__apirouter__field_indices_by_name[] = {
  1,   /* field[1] = api */
  0,   /* field[0] = service_name */
  2,   /* field[2] = tags */
};
static const ProtobufCIntRange ingress__apirouter__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ingress__apirouter__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ingress.APIRouter",
  "APIRouter",
  "Ingress__APIRouter",
  "Ingress",
  sizeof(Ingress__APIRouter),
  3,
  ingress__apirouter__field_descriptors,
  ingress__apirouter__field_indices_by_name,
  1,  ingress__apirouter__number_ranges,
  (ProtobufCMessageInit) ingress__apirouter__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ingress__router__field_descriptors[3] =
{
  {
    "host_router",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ingress__Router, host_router),
    &ingress__host_router__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "appname_router",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ingress__Router, appname_router),
    &ingress__appname_router__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "api_router",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ingress__Router, api_router),
    &ingress__apirouter__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ingress__router__field_indices_by_name[] = {
  2,   /* field[2] = api_router */
  1,   /* field[1] = appname_router */
  0,   /* field[0] = host_router */
};
static const ProtobufCIntRange ingress__router__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ingress__router__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ingress.Router",
  "Router",
  "Ingress__Router",
  "Ingress",
  sizeof(Ingress__Router),
  3,
  ingress__router__field_descriptors,
  ingress__router__field_indices_by_name,
  1,  ingress__router__number_ranges,
  (ProtobufCMessageInit) ingress__router__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ingress__timeout__field_descriptors[3] =
{
  {
    "connect_timeout",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Ingress__Timeout, has_connect_timeout),
    offsetof(Ingress__Timeout, connect_timeout),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "read_timeout",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Ingress__Timeout, has_read_timeout),
    offsetof(Ingress__Timeout, read_timeout),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "write_timeout",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Ingress__Timeout, has_write_timeout),
    offsetof(Ingress__Timeout, write_timeout),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ingress__timeout__field_indices_by_name[] = {
  0,   /* field[0] = connect_timeout */
  1,   /* field[1] = read_timeout */
  2,   /* field[2] = write_timeout */
};
static const ProtobufCIntRange ingress__timeout__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ingress__timeout__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ingress.Timeout",
  "Timeout",
  "Ingress__Timeout",
  "Ingress",
  sizeof(Ingress__Timeout),
  3,
  ingress__timeout__field_descriptors,
  ingress__timeout__field_indices_by_name,
  1,  ingress__timeout__number_ranges,
  (ProtobufCMessageInit) ingress__timeout__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ingress__upstream__field_descriptors[2] =
{
  {
    "target",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ingress__Upstream, target),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "weight",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Ingress__Upstream, has_weight),
    offsetof(Ingress__Upstream, weight),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ingress__upstream__field_indices_by_name[] = {
  0,   /* field[0] = target */
  1,   /* field[1] = weight */
};
static const ProtobufCIntRange ingress__upstream__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ingress__upstream__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ingress.Upstream",
  "Upstream",
  "Ingress__Upstream",
  "Ingress",
  sizeof(Ingress__Upstream),
  2,
  ingress__upstream__field_descriptors,
  ingress__upstream__field_indices_by_name,
  1,  ingress__upstream__number_ranges,
  (ProtobufCMessageInit) ingress__upstream__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ingress__metadata__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ingress__Metadata, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ingress__Metadata, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ingress__metadata__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange ingress__metadata__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ingress__metadata__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ingress.Metadata",
  "Metadata",
  "Ingress__Metadata",
  "Ingress",
  sizeof(Ingress__Metadata),
  2,
  ingress__metadata__field_descriptors,
  ingress__metadata__field_indices_by_name,
  1,  ingress__metadata__number_ranges,
  (ProtobufCMessageInit) ingress__metadata__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ingress__action__field_descriptors[4] =
{
  {
    "action_type",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Ingress__Action, has_action_type),
    offsetof(Ingress__Action, action_type),
    &ingress__action_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value_type",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Ingress__Action, has_value_type),
    offsetof(Ingress__Action, value_type),
    &ingress__action_value_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ingress__Action, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ingress__Action, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ingress__action__field_indices_by_name[] = {
  0,   /* field[0] = action_type */
  2,   /* field[2] = key */
  3,   /* field[3] = value */
  1,   /* field[1] = value_type */
};
static const ProtobufCIntRange ingress__action__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor ingress__action__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ingress.Action",
  "Action",
  "Ingress__Action",
  "Ingress",
  sizeof(Ingress__Action),
  4,
  ingress__action__field_descriptors,
  ingress__action__field_indices_by_name,
  1,  ingress__action__number_ranges,
  (ProtobufCMessageInit) ingress__action__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ingress__unit_redirect__field_descriptors[2] =
{
  {
    "from",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ingress__UnitRedirect, from),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "to",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ingress__UnitRedirect, to),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ingress__unit_redirect__field_indices_by_name[] = {
  0,   /* field[0] = from */
  1,   /* field[1] = to */
};
static const ProtobufCIntRange ingress__unit_redirect__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ingress__unit_redirect__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ingress.UnitRedirect",
  "UnitRedirect",
  "Ingress__UnitRedirect",
  "Ingress",
  sizeof(Ingress__UnitRedirect),
  2,
  ingress__unit_redirect__field_descriptors,
  ingress__unit_redirect__field_indices_by_name,
  1,  ingress__unit_redirect__number_ranges,
  (ProtobufCMessageInit) ingress__unit_redirect__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ingress__unit_weight__field_descriptors[3] =
{
  {
    "unit",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ingress__UnitWeight, unit),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "weight",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Ingress__UnitWeight, has_weight),
    offsetof(Ingress__UnitWeight, weight),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "consistent_hashing",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Ingress__UnitWeight, has_consistent_hashing),
    offsetof(Ingress__UnitWeight, consistent_hashing),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ingress__unit_weight__field_indices_by_name[] = {
  2,   /* field[2] = consistent_hashing */
  0,   /* field[0] = unit */
  1,   /* field[1] = weight */
};
static const ProtobufCIntRange ingress__unit_weight__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ingress__unit_weight__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ingress.UnitWeight",
  "UnitWeight",
  "Ingress__UnitWeight",
  "Ingress",
  sizeof(Ingress__UnitWeight),
  3,
  ingress__unit_weight__field_descriptors,
  ingress__unit_weight__field_indices_by_name,
  1,  ingress__unit_weight__number_ranges,
  (ProtobufCMessageInit) ingress__unit_weight__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ingress__unit__field_descriptors[3] =
{
  {
    "generic_unit",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ingress__Unit, generic_unit),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "redirects",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ingress__Unit, n_redirects),
    offsetof(Ingress__Unit, redirects),
    &ingress__unit_redirect__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "weights",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ingress__Unit, n_weights),
    offsetof(Ingress__Unit, weights),
    &ingress__unit_weight__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ingress__unit__field_indices_by_name[] = {
  0,   /* field[0] = generic_unit */
  1,   /* field[1] = redirects */
  2,   /* field[2] = weights */
};
static const ProtobufCIntRange ingress__unit__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ingress__unit__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ingress.Unit",
  "Unit",
  "Ingress__Unit",
  "Ingress",
  sizeof(Ingress__Unit),
  3,
  ingress__unit__field_descriptors,
  ingress__unit__field_indices_by_name,
  1,  ingress__unit__number_ranges,
  (ProtobufCMessageInit) ingress__unit__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ingress__redirect__field_descriptors[1] =
{
  {
    "host",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ingress__Redirect, host),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ingress__redirect__field_indices_by_name[] = {
  0,   /* field[0] = host */
};
static const ProtobufCIntRange ingress__redirect__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ingress__redirect__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ingress.Redirect",
  "Redirect",
  "Ingress__Redirect",
  "Ingress",
  sizeof(Ingress__Redirect),
  1,
  ingress__redirect__field_descriptors,
  ingress__redirect__field_indices_by_name,
  1,  ingress__redirect__number_ranges,
  (ProtobufCMessageInit) ingress__redirect__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ingress__failover_rule__field_descriptors[4] =
{
  {
    "err_codes",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Ingress__FailoverRule, n_err_codes),
    offsetof(Ingress__FailoverRule, err_codes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "upstreams",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ingress__FailoverRule, upstreams),
    &ingress__upstream__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timeout_ms",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ingress__FailoverRule, timeout_ms),
    &ingress__timeout__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "redirects",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ingress__FailoverRule, redirects),
    &ingress__redirect__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ingress__failover_rule__field_indices_by_name[] = {
  0,   /* field[0] = err_codes */
  3,   /* field[3] = redirects */
  2,   /* field[2] = timeout_ms */
  1,   /* field[1] = upstreams */
};
static const ProtobufCIntRange ingress__failover_rule__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor ingress__failover_rule__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ingress.FailoverRule",
  "FailoverRule",
  "Ingress__FailoverRule",
  "Ingress",
  sizeof(Ingress__FailoverRule),
  4,
  ingress__failover_rule__field_descriptors,
  ingress__failover_rule__field_indices_by_name,
  1,  ingress__failover_rule__number_ranges,
  (ProtobufCMessageInit) ingress__failover_rule__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ingress__failover__field_descriptors[1] =
{
  {
    "rules",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ingress__Failover, n_rules),
    offsetof(Ingress__Failover, rules),
    &ingress__failover_rule__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ingress__failover__field_indices_by_name[] = {
  0,   /* field[0] = rules */
};
static const ProtobufCIntRange ingress__failover__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ingress__failover__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ingress.Failover",
  "Failover",
  "Ingress__Failover",
  "Ingress",
  sizeof(Ingress__Failover),
  1,
  ingress__failover__field_descriptors,
  ingress__failover__field_indices_by_name,
  1,  ingress__failover__number_ranges,
  (ProtobufCMessageInit) ingress__failover__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ingress__virtual_service__field_descriptors[8] =
{
  {
    "service_name",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ingress__VirtualService, service_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "upstreams",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ingress__VirtualService, n_upstreams),
    offsetof(Ingress__VirtualService, upstreams),
    &ingress__upstream__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timeout_ms",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ingress__VirtualService, timeout_ms),
    &ingress__timeout__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "force_https",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Ingress__VirtualService, has_force_https),
    offsetof(Ingress__VirtualService, force_https),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "metadata",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ingress__VirtualService, n_metadata),
    offsetof(Ingress__VirtualService, metadata),
    &ingress__metadata__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "action",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ingress__VirtualService, n_action),
    offsetof(Ingress__VirtualService, action),
    &ingress__action__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "unit",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ingress__VirtualService, unit),
    &ingress__unit__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "failover",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ingress__VirtualService, n_failover),
    offsetof(Ingress__VirtualService, failover),
    &ingress__failover__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ingress__virtual_service__field_indices_by_name[] = {
  5,   /* field[5] = action */
  7,   /* field[7] = failover */
  3,   /* field[3] = force_https */
  4,   /* field[4] = metadata */
  0,   /* field[0] = service_name */
  2,   /* field[2] = timeout_ms */
  6,   /* field[6] = unit */
  1,   /* field[1] = upstreams */
};
static const ProtobufCIntRange ingress__virtual_service__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor ingress__virtual_service__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ingress.VirtualService",
  "VirtualService",
  "Ingress__VirtualService",
  "Ingress",
  sizeof(Ingress__VirtualService),
  8,
  ingress__virtual_service__field_descriptors,
  ingress__virtual_service__field_indices_by_name,
  1,  ingress__virtual_service__number_ranges,
  (ProtobufCMessageInit) ingress__virtual_service__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ingress__expire_time__field_descriptors[2] =
{
  {
    "seconds",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Ingress__ExpireTime, seconds),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nanoseconds",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Ingress__ExpireTime, nanoseconds),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ingress__expire_time__field_indices_by_name[] = {
  1,   /* field[1] = nanoseconds */
  0,   /* field[0] = seconds */
};
static const ProtobufCIntRange ingress__expire_time__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ingress__expire_time__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ingress.ExpireTime",
  "ExpireTime",
  "Ingress__ExpireTime",
  "Ingress",
  sizeof(Ingress__ExpireTime),
  2,
  ingress__expire_time__field_descriptors,
  ingress__expire_time__field_indices_by_name,
  1,  ingress__expire_time__number_ranges,
  (ProtobufCMessageInit) ingress__expire_time__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ingress__host_cert_entry__field_descriptors[3] =
{
  {
    "hostname",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ingress__HostCertEntry, hostname),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pem_data1",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ingress__HostCertEntry, pem_data1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pem_data2",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ingress__HostCertEntry, pem_data2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ingress__host_cert_entry__field_indices_by_name[] = {
  0,   /* field[0] = hostname */
  1,   /* field[1] = pem_data1 */
  2,   /* field[2] = pem_data2 */
};
static const ProtobufCIntRange ingress__host_cert_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ingress__host_cert_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ingress.HostCertEntry",
  "HostCertEntry",
  "Ingress__HostCertEntry",
  "Ingress",
  sizeof(Ingress__HostCertEntry),
  3,
  ingress__host_cert_entry__field_descriptors,
  ingress__host_cert_entry__field_indices_by_name,
  1,  ingress__host_cert_entry__number_ranges,
  (ProtobufCMessageInit) ingress__host_cert_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ingress__config__field_descriptors[3] =
{
  {
    "routers",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ingress__Config, n_routers),
    offsetof(Ingress__Config, routers),
    &ingress__router__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "services",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ingress__Config, n_services),
    offsetof(Ingress__Config, services),
    &ingress__virtual_service__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "host_certs",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ingress__Config, n_host_certs),
    offsetof(Ingress__Config, host_certs),
    &ingress__host_cert_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ingress__config__field_indices_by_name[] = {
  2,   /* field[2] = host_certs */
  0,   /* field[0] = routers */
  1,   /* field[1] = services */
};
static const ProtobufCIntRange ingress__config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ingress__config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ingress.Config",
  "Config",
  "Ingress__Config",
  "Ingress",
  sizeof(Ingress__Config),
  3,
  ingress__config__field_descriptors,
  ingress__config__field_indices_by_name,
  1,  ingress__config__number_ranges,
  (ProtobufCMessageInit) ingress__config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue ingress__location_type__enum_values_by_number[6] =
{
  { "LocUnDefined", "INGRESS__LOCATION_TYPE__LocUnDefined", 0 },
  { "LocHttpHeader", "INGRESS__LOCATION_TYPE__LocHttpHeader", 1 },
  { "LocHttpQuery", "INGRESS__LOCATION_TYPE__LocHttpQuery", 2 },
  { "LocNginxVar", "INGRESS__LOCATION_TYPE__LocNginxVar", 3 },
  { "LocXBizInfo", "INGRESS__LOCATION_TYPE__LocXBizInfo", 4 },
  { "LocHttpCookie", "INGRESS__LOCATION_TYPE__LocHttpCookie", 5 },
};
static const ProtobufCIntRange ingress__location_type__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex ingress__location_type__enum_values_by_name[6] =
{
  { "LocHttpCookie", 5 },
  { "LocHttpHeader", 1 },
  { "LocHttpQuery", 2 },
  { "LocNginxVar", 3 },
  { "LocUnDefined", 0 },
  { "LocXBizInfo", 4 },
};
const ProtobufCEnumDescriptor ingress__location_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Ingress.LocationType",
  "LocationType",
  "Ingress__LocationType",
  "Ingress",
  6,
  ingress__location_type__enum_values_by_number,
  6,
  ingress__location_type__enum_values_by_name,
  1,
  ingress__location_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue ingress__match_type__enum_values_by_number[4] =
{
  { "MatchUnDefined", "INGRESS__MATCH_TYPE__MatchUnDefined", 0 },
  { "WholeMatch", "INGRESS__MATCH_TYPE__WholeMatch", 1 },
  { "StrListInMatch", "INGRESS__MATCH_TYPE__StrListInMatch", 2 },
  { "ModCompare", "INGRESS__MATCH_TYPE__ModCompare", 3 },
};
static const ProtobufCIntRange ingress__match_type__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex ingress__match_type__enum_values_by_name[4] =
{
  { "MatchUnDefined", 0 },
  { "ModCompare", 3 },
  { "StrListInMatch", 2 },
  { "WholeMatch", 1 },
};
const ProtobufCEnumDescriptor ingress__match_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Ingress.MatchType",
  "MatchType",
  "Ingress__MatchType",
  "Ingress",
  4,
  ingress__match_type__enum_values_by_number,
  4,
  ingress__match_type__enum_values_by_name,
  1,
  ingress__match_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue ingress__operator_type__enum_values_by_number[6] =
{
  { "OperatorUnDefined", "INGRESS__OPERATOR_TYPE__OperatorUnDefined", 0 },
  { "OperatorEqual", "INGRESS__OPERATOR_TYPE__OperatorEqual", 1 },
  { "OperatorGreater", "INGRESS__OPERATOR_TYPE__OperatorGreater", 2 },
  { "OperatorLess", "INGRESS__OPERATOR_TYPE__OperatorLess", 3 },
  { "OperatorGreaterEqual", "INGRESS__OPERATOR_TYPE__OperatorGreaterEqual", 4 },
  { "OperatorLessEqual", "INGRESS__OPERATOR_TYPE__OperatorLessEqual", 5 },
};
static const ProtobufCIntRange ingress__operator_type__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex ingress__operator_type__enum_values_by_name[6] =
{
  { "OperatorEqual", 1 },
  { "OperatorGreater", 2 },
  { "OperatorGreaterEqual", 4 },
  { "OperatorLess", 3 },
  { "OperatorLessEqual", 5 },
  { "OperatorUnDefined", 0 },
};
const ProtobufCEnumDescriptor ingress__operator_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Ingress.OperatorType",
  "OperatorType",
  "Ingress__OperatorType",
  "Ingress",
  6,
  ingress__operator_type__enum_values_by_number,
  6,
  ingress__operator_type__enum_values_by_name,
  1,
  ingress__operator_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue ingress__action_type__enum_values_by_number[6] =
{
  { "ActionUnDefined", "INGRESS__ACTION_TYPE__ActionUnDefined", 0 },
  { "ActionAddReqHeader", "INGRESS__ACTION_TYPE__ActionAddReqHeader", 1 },
  { "ActionAppendReqHeader", "INGRESS__ACTION_TYPE__ActionAppendReqHeader", 2 },
  { "ActionAddRespHeader", "INGRESS__ACTION_TYPE__ActionAddRespHeader", 3 },
  { "ActionAppendRespHeader", "INGRESS__ACTION_TYPE__ActionAppendRespHeader", 4 },
  { "ActionAddParam", "INGRESS__ACTION_TYPE__ActionAddParam", 5 },
};
static const ProtobufCIntRange ingress__action_type__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex ingress__action_type__enum_values_by_name[6] =
{
  { "ActionAddParam", 5 },
  { "ActionAddReqHeader", 1 },
  { "ActionAddRespHeader", 3 },
  { "ActionAppendReqHeader", 2 },
  { "ActionAppendRespHeader", 4 },
  { "ActionUnDefined", 0 },
};
const ProtobufCEnumDescriptor ingress__action_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Ingress.ActionType",
  "ActionType",
  "Ingress__ActionType",
  "Ingress",
  6,
  ingress__action_type__enum_values_by_number,
  6,
  ingress__action_type__enum_values_by_name,
  1,
  ingress__action_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue ingress__action_value_type__enum_values_by_number[3] =
{
  { "ActionValueUnDefined", "INGRESS__ACTION_VALUE_TYPE__ActionValueUnDefined", 0 },
  { "ActionStaticValue", "INGRESS__ACTION_VALUE_TYPE__ActionStaticValue", 1 },
  { "ActionDynamicValue", "INGRESS__ACTION_VALUE_TYPE__ActionDynamicValue", 2 },
};
static const ProtobufCIntRange ingress__action_value_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex ingress__action_value_type__enum_values_by_name[3] =
{
  { "ActionDynamicValue", 2 },
  { "ActionStaticValue", 1 },
  { "ActionValueUnDefined", 0 },
};
const ProtobufCEnumDescriptor ingress__action_value_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Ingress.ActionValueType",
  "ActionValueType",
  "Ingress__ActionValueType",
  "Ingress",
  3,
  ingress__action_value_type__enum_values_by_number,
  3,
  ingress__action_value_type__enum_values_by_name,
  1,
  ingress__action_value_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue ingress__host_type__enum_values_by_number[3] =
{
  { "Web", "INGRESS__HOST_TYPE__Web", 0 },
  { "MTOP", "INGRESS__HOST_TYPE__MTOP", 1 },
  { "MCP", "INGRESS__HOST_TYPE__MCP", 2 },
};
static const ProtobufCIntRange ingress__host_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex ingress__host_type__enum_values_by_name[3] =
{
  { "MCP", 2 },
  { "MTOP", 1 },
  { "Web", 0 },
};
const ProtobufCEnumDescriptor ingress__host_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Ingress.HostType",
  "HostType",
  "Ingress__HostType",
  "Ingress",
  3,
  ingress__host_type__enum_values_by_number,
  3,
  ingress__host_type__enum_values_by_name,
  1,
  ingress__host_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
