/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ingress.proto */

#ifndef PROTOBUF_C_ingress_2eproto__INCLUDED
#define PROTOBUF_C_ingress_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Ingress__TagValueStrList Ingress__TagValueStrList;
typedef struct _Ingress__TagItemCondition Ingress__TagItemCondition;
typedef struct _Ingress__TagItem Ingress__TagItem;
typedef struct _Ingress__TagRule Ingress__TagRule;
typedef struct _Ingress__TagRouter Ingress__TagRouter;
typedef struct _Ingress__PathRouter Ingress__PathRouter;
typedef struct _Ingress__HostRouter Ingress__HostRouter;
typedef struct _Ingress__AppnameRouter Ingress__AppnameRouter;
typedef struct _Ingress__APIRouter Ingress__APIRouter;
typedef struct _Ingress__Router Ingress__Router;
typedef struct _Ingress__Timeout Ingress__Timeout;
typedef struct _Ingress__Upstream Ingress__Upstream;
typedef struct _Ingress__Metadata Ingress__Metadata;
typedef struct _Ingress__Action Ingress__Action;
typedef struct _Ingress__VirtualService Ingress__VirtualService;
typedef struct _Ingress__Config Ingress__Config;


/* --- enums --- */

typedef enum _Ingress__LocationType {
  /*
   * first element must be zero
   */
  INGRESS__LOCATION_TYPE__LocUnDefined = 0,
  /*
   * Tag from http header
   */
  INGRESS__LOCATION_TYPE__LocHttpHeader = 1,
  /*
   * Tag from http query 
   */
  INGRESS__LOCATION_TYPE__LocHttpQuery = 2,
  /*
   * Tag from nginx var 
   */
  INGRESS__LOCATION_TYPE__LocNginxVar = 3,
  /*
   * Tag from x-biz-info 
   */
  INGRESS__LOCATION_TYPE__LocXBizInfo = 4,
  /*
   * Tag from http cookie
   */
  INGRESS__LOCATION_TYPE__LocHttpCookie = 5
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(INGRESS__LOCATION_TYPE)
} Ingress__LocationType;
typedef enum _Ingress__MatchType {
  /*
   * first element must be zero
   */
  INGRESS__MATCH_TYPE__MatchUnDefined = 0,
  /*
   * String matches exactly
   */
  INGRESS__MATCH_TYPE__WholeMatch = 1,
  /*
   * String list match
   */
  INGRESS__MATCH_TYPE__StrListInMatch = 2,
  /*
   * mod result compare value
   */
  INGRESS__MATCH_TYPE__ModCompare = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(INGRESS__MATCH_TYPE)
} Ingress__MatchType;
typedef enum _Ingress__OperatorType {
  /*
   * first element must be zero
   */
  INGRESS__OPERATOR_TYPE__OperatorUnDefined = 0,
  /*
   * equal operation
   */
  INGRESS__OPERATOR_TYPE__OperatorEqual = 1,
  /*
   * greater operation
   */
  INGRESS__OPERATOR_TYPE__OperatorGreater = 2,
  /*
   * less operation
   */
  INGRESS__OPERATOR_TYPE__OperatorLess = 3,
  /*
   * greater or equal 
   */
  INGRESS__OPERATOR_TYPE__OperatorGreaterEqual = 4,
  /*
   * less or equal
   */
  INGRESS__OPERATOR_TYPE__OperatorLessEqual = 5
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(INGRESS__OPERATOR_TYPE)
} Ingress__OperatorType;
typedef enum _Ingress__ActionType {
  /*
   * first element must be zero
   */
  INGRESS__ACTION_TYPE__ActionUnDefined = 0,
  /*
   * Action add http request header, add action do not care about duplicate
   */
  INGRESS__ACTION_TYPE__ActionAddReqHeader = 1,
  /*
   * Action append http request header
   */
  INGRESS__ACTION_TYPE__ActionAppendReqHeader = 2,
  /*
   * Action add http response header
   */
  INGRESS__ACTION_TYPE__ActionAddRespHeader = 3,
  /*
   * Action append http response header
   */
  INGRESS__ACTION_TYPE__ActionAppendRespHeader = 4,
  /*
   * Action add http request query param
   */
  INGRESS__ACTION_TYPE__ActionAddParam = 5
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(INGRESS__ACTION_TYPE)
} Ingress__ActionType;
typedef enum _Ingress__ActionValueType {
  /*
   *first element must be zero
   */
  INGRESS__ACTION_VALUE_TYPE__ActionValueUnDefined = 0,
  /*
   * value from configure
   */
  INGRESS__ACTION_VALUE_TYPE__ActionStaticValue = 1,
  /*
   * value from nginx var
   */
  INGRESS__ACTION_VALUE_TYPE__ActionDynamicValue = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(INGRESS__ACTION_VALUE_TYPE)
} Ingress__ActionValueType;

/* --- messages --- */

struct  _Ingress__TagValueStrList
{
  ProtobufCMessage base;
  /*
   * string list  
   */
  size_t n_value;
  char **value;
};
#define INGRESS__TAG_VALUE_STR_LIST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ingress__tag_value_str_list__descriptor) \
    , 0,NULL }


struct  _Ingress__TagItemCondition
{
  ProtobufCMessage base;
  /*
   * string match value, for WholeMatch,PrefixMatch,SuffixMatch, and RegMatch
   */
  char *value_str;
  /*
   * string list for match, for StrListInMatch
   */
  Ingress__TagValueStrList *value_list;
  /*
   * mode divisor, for ModCompare
   */
  protobuf_c_boolean has_divisor;
  uint64_t divisor;
  /*
   * compare remainder, for ModCompare
   */
  protobuf_c_boolean has_remainder;
  uint64_t remainder;
  /*
   * >, <, =, >=, <=, for ModCompare
   */
  protobuf_c_boolean has_operator_;
  Ingress__OperatorType operator_;
};
#define INGRESS__TAG_ITEM_CONDITION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ingress__tag_item_condition__descriptor) \
    , NULL, NULL, 0, 0, 0, 0, 0, INGRESS__OPERATOR_TYPE__OperatorUnDefined }


struct  _Ingress__TagItem
{
  ProtobufCMessage base;
  /*
   * which location to get the Tag
   */
  protobuf_c_boolean has_location;
  Ingress__LocationType location;
  /*
   * The name of the key to be parsed
   */
  char *key;
  /*
   * The name of the value to be parsed
   */
  Ingress__TagItemCondition *condition;
  /*
   * matching method
   */
  protobuf_c_boolean has_match_type;
  Ingress__MatchType match_type;
};
#define INGRESS__TAG_ITEM__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ingress__tag_item__descriptor) \
    , 0, INGRESS__LOCATION_TYPE__LocUnDefined, NULL, NULL, 0, INGRESS__MATCH_TYPE__MatchUnDefined }


struct  _Ingress__TagRule
{
  ProtobufCMessage base;
  /*
   * 'and' condition
   */
  size_t n_items;
  Ingress__TagItem **items;
};
#define INGRESS__TAG_RULE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ingress__tag_rule__descriptor) \
    , 0,NULL }


struct  _Ingress__TagRouter
{
  ProtobufCMessage base;
  char *service_name;
  /*
   * 'or' condition
   */
  size_t n_rules;
  Ingress__TagRule **rules;
};
#define INGRESS__TAG_ROUTER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ingress__tag_router__descriptor) \
    , NULL, 0,NULL }


struct  _Ingress__PathRouter
{
  ProtobufCMessage base;
  char *prefix;
  char *service_name;
  size_t n_tags;
  Ingress__TagRouter **tags;
};
#define INGRESS__PATH_ROUTER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ingress__path_router__descriptor) \
    , NULL, NULL, 0,NULL }


struct  _Ingress__HostRouter
{
  ProtobufCMessage base;
  char *host;
  char *service_name;
  size_t n_paths;
  Ingress__PathRouter **paths;
  size_t n_tags;
  Ingress__TagRouter **tags;
};
#define INGRESS__HOST_ROUTER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ingress__host_router__descriptor) \
    , NULL, NULL, 0,NULL, 0,NULL }


struct  _Ingress__AppnameRouter
{
  ProtobufCMessage base;
  char *appname;
  char *service_name;
  size_t n_tags;
  Ingress__TagRouter **tags;
};
#define INGRESS__APPNAME_ROUTER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ingress__appname_router__descriptor) \
    , NULL, NULL, 0,NULL }


struct  _Ingress__APIRouter
{
  ProtobufCMessage base;
  char *service_name;
  char *api;
  size_t n_tags;
  Ingress__TagRouter **tags;
};
#define INGRESS__APIROUTER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ingress__apirouter__descriptor) \
    , NULL, NULL, 0,NULL }


struct  _Ingress__Router
{
  ProtobufCMessage base;
  Ingress__HostRouter *host_router;
  Ingress__AppnameRouter *appname_router;
  Ingress__APIRouter *api_router;
};
#define INGRESS__ROUTER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ingress__router__descriptor) \
    , NULL, NULL, NULL }


struct  _Ingress__Timeout
{
  ProtobufCMessage base;
  protobuf_c_boolean has_connect_timeout;
  uint32_t connect_timeout;
  protobuf_c_boolean has_read_timeout;
  uint32_t read_timeout;
  protobuf_c_boolean has_write_timeout;
  uint32_t write_timeout;
};
#define INGRESS__TIMEOUT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ingress__timeout__descriptor) \
    , 0, 0, 0, 0, 0, 0 }


struct  _Ingress__Upstream
{
  ProtobufCMessage base;
  char *target;
  protobuf_c_boolean has_weight;
  uint32_t weight;
};
#define INGRESS__UPSTREAM__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ingress__upstream__descriptor) \
    , NULL, 0, 0 }


struct  _Ingress__Metadata
{
  ProtobufCMessage base;
  char *key;
  char *value;
};
#define INGRESS__METADATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ingress__metadata__descriptor) \
    , NULL, NULL }


struct  _Ingress__Action
{
  ProtobufCMessage base;
  /*
   * action type 
   */
  protobuf_c_boolean has_action_type;
  Ingress__ActionType action_type;
  /*
   * action value type
   */
  protobuf_c_boolean has_value_type;
  Ingress__ActionValueType value_type;
  /*
   * action key
   */
  char *key;
  /*
   * action value
   */
  char *value;
};
#define INGRESS__ACTION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ingress__action__descriptor) \
    , 0, INGRESS__ACTION_TYPE__ActionUnDefined, 0, INGRESS__ACTION_VALUE_TYPE__ActionValueUnDefined, NULL, NULL }
struct  _Ingress__VirtualService
{
  ProtobufCMessage base;
  char *service_name;
  size_t n_upstreams;
  Ingress__Upstream **upstreams;
  Ingress__Timeout *timeout_ms;
  protobuf_c_boolean has_force_https;
  protobuf_c_boolean force_https;
  size_t n_metadata;
  Ingress__Metadata **metadata;
  size_t n_action;
  Ingress__Action **action;
};
#define INGRESS__VIRTUAL_SERVICE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ingress__virtual_service__descriptor) \
    , NULL, 0,NULL, NULL, 0, 0, 0,NULL, 0,NULL }


struct  _Ingress__Config
{
  ProtobufCMessage base;
  size_t n_routers;
  Ingress__Router **routers;
  size_t n_services;
  Ingress__VirtualService **services;
};
#define INGRESS__CONFIG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ingress__config__descriptor) \
    , 0,NULL, 0,NULL }


/* Ingress__TagValueStrList methods */
void   ingress__tag_value_str_list__init
                     (Ingress__TagValueStrList         *message);
size_t ingress__tag_value_str_list__get_packed_size
                     (const Ingress__TagValueStrList   *message);
size_t ingress__tag_value_str_list__pack
                     (const Ingress__TagValueStrList   *message,
                      uint8_t             *out);
size_t ingress__tag_value_str_list__pack_to_buffer
                     (const Ingress__TagValueStrList   *message,
                      ProtobufCBuffer     *buffer);
Ingress__TagValueStrList *
       ingress__tag_value_str_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ingress__tag_value_str_list__free_unpacked
                     (Ingress__TagValueStrList *message,
                      ProtobufCAllocator *allocator);
/* Ingress__TagItemCondition methods */
void   ingress__tag_item_condition__init
                     (Ingress__TagItemCondition         *message);
size_t ingress__tag_item_condition__get_packed_size
                     (const Ingress__TagItemCondition   *message);
size_t ingress__tag_item_condition__pack
                     (const Ingress__TagItemCondition   *message,
                      uint8_t             *out);
size_t ingress__tag_item_condition__pack_to_buffer
                     (const Ingress__TagItemCondition   *message,
                      ProtobufCBuffer     *buffer);
Ingress__TagItemCondition *
       ingress__tag_item_condition__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ingress__tag_item_condition__free_unpacked
                     (Ingress__TagItemCondition *message,
                      ProtobufCAllocator *allocator);
/* Ingress__TagItem methods */
void   ingress__tag_item__init
                     (Ingress__TagItem         *message);
size_t ingress__tag_item__get_packed_size
                     (const Ingress__TagItem   *message);
size_t ingress__tag_item__pack
                     (const Ingress__TagItem   *message,
                      uint8_t             *out);
size_t ingress__tag_item__pack_to_buffer
                     (const Ingress__TagItem   *message,
                      ProtobufCBuffer     *buffer);
Ingress__TagItem *
       ingress__tag_item__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ingress__tag_item__free_unpacked
                     (Ingress__TagItem *message,
                      ProtobufCAllocator *allocator);
/* Ingress__TagRule methods */
void   ingress__tag_rule__init
                     (Ingress__TagRule         *message);
size_t ingress__tag_rule__get_packed_size
                     (const Ingress__TagRule   *message);
size_t ingress__tag_rule__pack
                     (const Ingress__TagRule   *message,
                      uint8_t             *out);
size_t ingress__tag_rule__pack_to_buffer
                     (const Ingress__TagRule   *message,
                      ProtobufCBuffer     *buffer);
Ingress__TagRule *
       ingress__tag_rule__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ingress__tag_rule__free_unpacked
                     (Ingress__TagRule *message,
                      ProtobufCAllocator *allocator);
/* Ingress__TagRouter methods */
void   ingress__tag_router__init
                     (Ingress__TagRouter         *message);
size_t ingress__tag_router__get_packed_size
                     (const Ingress__TagRouter   *message);
size_t ingress__tag_router__pack
                     (const Ingress__TagRouter   *message,
                      uint8_t             *out);
size_t ingress__tag_router__pack_to_buffer
                     (const Ingress__TagRouter   *message,
                      ProtobufCBuffer     *buffer);
Ingress__TagRouter *
       ingress__tag_router__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ingress__tag_router__free_unpacked
                     (Ingress__TagRouter *message,
                      ProtobufCAllocator *allocator);
/* Ingress__PathRouter methods */
void   ingress__path_router__init
                     (Ingress__PathRouter         *message);
size_t ingress__path_router__get_packed_size
                     (const Ingress__PathRouter   *message);
size_t ingress__path_router__pack
                     (const Ingress__PathRouter   *message,
                      uint8_t             *out);
size_t ingress__path_router__pack_to_buffer
                     (const Ingress__PathRouter   *message,
                      ProtobufCBuffer     *buffer);
Ingress__PathRouter *
       ingress__path_router__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ingress__path_router__free_unpacked
                     (Ingress__PathRouter *message,
                      ProtobufCAllocator *allocator);
/* Ingress__HostRouter methods */
void   ingress__host_router__init
                     (Ingress__HostRouter         *message);
size_t ingress__host_router__get_packed_size
                     (const Ingress__HostRouter   *message);
size_t ingress__host_router__pack
                     (const Ingress__HostRouter   *message,
                      uint8_t             *out);
size_t ingress__host_router__pack_to_buffer
                     (const Ingress__HostRouter   *message,
                      ProtobufCBuffer     *buffer);
Ingress__HostRouter *
       ingress__host_router__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ingress__host_router__free_unpacked
                     (Ingress__HostRouter *message,
                      ProtobufCAllocator *allocator);
/* Ingress__AppnameRouter methods */
void   ingress__appname_router__init
                     (Ingress__AppnameRouter         *message);
size_t ingress__appname_router__get_packed_size
                     (const Ingress__AppnameRouter   *message);
size_t ingress__appname_router__pack
                     (const Ingress__AppnameRouter   *message,
                      uint8_t             *out);
size_t ingress__appname_router__pack_to_buffer
                     (const Ingress__AppnameRouter   *message,
                      ProtobufCBuffer     *buffer);
Ingress__AppnameRouter *
       ingress__appname_router__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ingress__appname_router__free_unpacked
                     (Ingress__AppnameRouter *message,
                      ProtobufCAllocator *allocator);
/* Ingress__APIRouter methods */
void   ingress__apirouter__init
                     (Ingress__APIRouter         *message);
size_t ingress__apirouter__get_packed_size
                     (const Ingress__APIRouter   *message);
size_t ingress__apirouter__pack
                     (const Ingress__APIRouter   *message,
                      uint8_t             *out);
size_t ingress__apirouter__pack_to_buffer
                     (const Ingress__APIRouter   *message,
                      ProtobufCBuffer     *buffer);
Ingress__APIRouter *
       ingress__apirouter__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ingress__apirouter__free_unpacked
                     (Ingress__APIRouter *message,
                      ProtobufCAllocator *allocator);
/* Ingress__Router methods */
void   ingress__router__init
                     (Ingress__Router         *message);
size_t ingress__router__get_packed_size
                     (const Ingress__Router   *message);
size_t ingress__router__pack
                     (const Ingress__Router   *message,
                      uint8_t             *out);
size_t ingress__router__pack_to_buffer
                     (const Ingress__Router   *message,
                      ProtobufCBuffer     *buffer);
Ingress__Router *
       ingress__router__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ingress__router__free_unpacked
                     (Ingress__Router *message,
                      ProtobufCAllocator *allocator);
/* Ingress__Timeout methods */
void   ingress__timeout__init
                     (Ingress__Timeout         *message);
size_t ingress__timeout__get_packed_size
                     (const Ingress__Timeout   *message);
size_t ingress__timeout__pack
                     (const Ingress__Timeout   *message,
                      uint8_t             *out);
size_t ingress__timeout__pack_to_buffer
                     (const Ingress__Timeout   *message,
                      ProtobufCBuffer     *buffer);
Ingress__Timeout *
       ingress__timeout__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ingress__timeout__free_unpacked
                     (Ingress__Timeout *message,
                      ProtobufCAllocator *allocator);
/* Ingress__Upstream methods */
void   ingress__upstream__init
                     (Ingress__Upstream         *message);
size_t ingress__upstream__get_packed_size
                     (const Ingress__Upstream   *message);
size_t ingress__upstream__pack
                     (const Ingress__Upstream   *message,
                      uint8_t             *out);
size_t ingress__upstream__pack_to_buffer
                     (const Ingress__Upstream   *message,
                      ProtobufCBuffer     *buffer);
Ingress__Upstream *
       ingress__upstream__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ingress__upstream__free_unpacked
                     (Ingress__Upstream *message,
                      ProtobufCAllocator *allocator);
/* Ingress__Metadata methods */
void   ingress__metadata__init
                     (Ingress__Metadata         *message);
size_t ingress__metadata__get_packed_size
                     (const Ingress__Metadata   *message);
size_t ingress__metadata__pack
                     (const Ingress__Metadata   *message,
                      uint8_t             *out);
size_t ingress__metadata__pack_to_buffer
                     (const Ingress__Metadata   *message,
                      ProtobufCBuffer     *buffer);
Ingress__Metadata *
       ingress__metadata__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ingress__metadata__free_unpacked
                     (Ingress__Metadata *message,
                      ProtobufCAllocator *allocator);
/* Ingress__Action methods */
void   ingress__action__init
                     (Ingress__Action         *message);
size_t ingress__action__get_packed_size
                     (const Ingress__Action   *message);
size_t ingress__action__pack
                     (const Ingress__Action   *message,
                      uint8_t             *out);
size_t ingress__action__pack_to_buffer
                     (const Ingress__Action   *message,
                      ProtobufCBuffer     *buffer);
Ingress__Action *
       ingress__action__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ingress__action__free_unpacked
                     (Ingress__Action *message,
                      ProtobufCAllocator *allocator);
/* Ingress__VirtualService methods */
void   ingress__virtual_service__init
                     (Ingress__VirtualService         *message);
size_t ingress__virtual_service__get_packed_size
                     (const Ingress__VirtualService   *message);
size_t ingress__virtual_service__pack
                     (const Ingress__VirtualService   *message,
                      uint8_t             *out);
size_t ingress__virtual_service__pack_to_buffer
                     (const Ingress__VirtualService   *message,
                      ProtobufCBuffer     *buffer);
Ingress__VirtualService *
       ingress__virtual_service__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ingress__virtual_service__free_unpacked
                     (Ingress__VirtualService *message,
                      ProtobufCAllocator *allocator);
/* Ingress__Config methods */
void   ingress__config__init
                     (Ingress__Config         *message);
size_t ingress__config__get_packed_size
                     (const Ingress__Config   *message);
size_t ingress__config__pack
                     (const Ingress__Config   *message,
                      uint8_t             *out);
size_t ingress__config__pack_to_buffer
                     (const Ingress__Config   *message,
                      ProtobufCBuffer     *buffer);
Ingress__Config *
       ingress__config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ingress__config__free_unpacked
                     (Ingress__Config *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Ingress__TagValueStrList_Closure)
                 (const Ingress__TagValueStrList *message,
                  void *closure_data);
typedef void (*Ingress__TagItemCondition_Closure)
                 (const Ingress__TagItemCondition *message,
                  void *closure_data);
typedef void (*Ingress__TagItem_Closure)
                 (const Ingress__TagItem *message,
                  void *closure_data);
typedef void (*Ingress__TagRule_Closure)
                 (const Ingress__TagRule *message,
                  void *closure_data);
typedef void (*Ingress__TagRouter_Closure)
                 (const Ingress__TagRouter *message,
                  void *closure_data);
typedef void (*Ingress__PathRouter_Closure)
                 (const Ingress__PathRouter *message,
                  void *closure_data);
typedef void (*Ingress__HostRouter_Closure)
                 (const Ingress__HostRouter *message,
                  void *closure_data);
typedef void (*Ingress__AppnameRouter_Closure)
                 (const Ingress__AppnameRouter *message,
                  void *closure_data);
typedef void (*Ingress__APIRouter_Closure)
                 (const Ingress__APIRouter *message,
                  void *closure_data);
typedef void (*Ingress__Router_Closure)
                 (const Ingress__Router *message,
                  void *closure_data);
typedef void (*Ingress__Timeout_Closure)
                 (const Ingress__Timeout *message,
                  void *closure_data);
typedef void (*Ingress__Upstream_Closure)
                 (const Ingress__Upstream *message,
                  void *closure_data);
typedef void (*Ingress__Metadata_Closure)
                 (const Ingress__Metadata *message,
                  void *closure_data);
typedef void (*Ingress__Action_Closure)
                 (const Ingress__Action *message,
                  void *closure_data);
typedef void (*Ingress__VirtualService_Closure)
                 (const Ingress__VirtualService *message,
                  void *closure_data);
typedef void (*Ingress__Config_Closure)
                 (const Ingress__Config *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    ingress__location_type__descriptor;
extern const ProtobufCEnumDescriptor    ingress__match_type__descriptor;
extern const ProtobufCEnumDescriptor    ingress__operator_type__descriptor;
extern const ProtobufCEnumDescriptor    ingress__action_type__descriptor;
extern const ProtobufCEnumDescriptor    ingress__action_value_type__descriptor;
extern const ProtobufCMessageDescriptor ingress__tag_value_str_list__descriptor;
extern const ProtobufCMessageDescriptor ingress__tag_item_condition__descriptor;
extern const ProtobufCMessageDescriptor ingress__tag_item__descriptor;
extern const ProtobufCMessageDescriptor ingress__tag_rule__descriptor;
extern const ProtobufCMessageDescriptor ingress__tag_router__descriptor;
extern const ProtobufCMessageDescriptor ingress__path_router__descriptor;
extern const ProtobufCMessageDescriptor ingress__host_router__descriptor;
extern const ProtobufCMessageDescriptor ingress__appname_router__descriptor;
extern const ProtobufCMessageDescriptor ingress__apirouter__descriptor;
extern const ProtobufCMessageDescriptor ingress__router__descriptor;
extern const ProtobufCMessageDescriptor ingress__timeout__descriptor;
extern const ProtobufCMessageDescriptor ingress__upstream__descriptor;
extern const ProtobufCMessageDescriptor ingress__metadata__descriptor;
extern const ProtobufCMessageDescriptor ingress__action__descriptor;
extern const ProtobufCMessageDescriptor ingress__virtual_service__descriptor;
extern const ProtobufCMessageDescriptor ingress__config__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_ingress_2eproto__INCLUDED */
